### ISSUE TITLE
Support IDA 9.2

### ISSUE THREAD

**Issue by Still34** [KasperskyLab/hrtng#36]
**Describe the bug**
The latest release currently support up to IDA 9.1, and the current source code does not compile with the latest IDA SDK. IDA appears to have deprecated the `cc` member.

```diff
struct func_type_data_t : public funcargvec_t // #func
{
[...]
- cm_t cc = CM_CC_UNKNOWN;  ///< calling convention
+ cm_t _old_cc = CM_CC_UNKNOWN; // calling convention, legacy codes. do not access
[...]
}
```

**To Reproduce**
1. Build with the latest 9.2 SDK
2. Be greeted with `error C2039: 'cc': is not a member of 'func_type_data_t'`

**Expected behavior**
Successful build.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDA version: 9.2 Pro
 - hrtng plugin version: hrtng-2.7.63
 - installed 3rd party plugins details: N/A

**Additional context**
